import type { Metadata } from "next";
import { EB_Garamond, Libre_Baskerville, Domine } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./providers/authProvider";
import Header from "./components/header/Header";

const libreBaskerville = Libre_Baskerville({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={libreBaskerville.className}>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
