import type { Metadata } from "next";
import {  Libre_Baskerville} from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./providers/authProvider";
import PostProvider from "./providers/postProvider";
import Header from "./components/header/Header";


const libreBaskerville = Libre_Baskerville({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-one">
      <body className={libreBaskerville.className}>
        <AuthProvider>
          <PostProvider>
              <Header />
              {children}
          </PostProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
